FROM python:3.10.0
WORKDIR /code
COPY src/currencyAPI /code
COPY src/currencyAPI/requirements.txt /code/requirements.txt 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
# uvicorn serves requests
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--workers", "2"]
