apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: <COHORT><TEAM>devcurrency
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: production-support-course
  filterTags:
    pattern: '^<COHORT><TEAM>currencyapi-dev-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
