name: Build-Deliver-Images
on: 
  push:
    branches:
      - main

jobs:
  Build-To-ECR:
    runs-on: [self-hosted, eks-sre-infra]
    env:
      ECR_REPOSITORY: "production-support-course"
      ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
      COHORT: 'c397'
      TEAM: 'team04'
      #semantic-release-num: ${{ env.semantic-release-num }}
    steps:
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Front End
        id: push-img-fe
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: production-support-course
          IMAGE_TAG: "${{env.cohort}}${{env.team}}fe-dev-${{ github.run_number }}"
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG -f Dockerfile_nginx ${{ github.workspace }}/Dockerfiles 
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

      - name: Build and Push DB
        id: push-img-db
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: production-support-course
          IMAGE_TAG: "${{env.cohort}}${{env.team}}db-dev-${{ github.run_number }}"
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql ${{ github.workspace }}/Dockerfiles 
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

      - name: Build and Push api
        id: push-img-api
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: production-support-course
          IMAGE_TAG: "${{env.cohort}}${{env.team}}api-dev-${{ github.run_number }}"
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG -f Dockerfile_fastapi ${{ github.workspace }}/Dockerfiles 
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        
