name: Build-Deliver-Images
on: 
  push:
    branches:
      - main

jobs:
  Build-To-ECR:
    runs-on: [self-hosted, eks-sre-infra]
    env:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: "production-support-course"
      ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
      COHORT: 'c397'
      TEAM: 'team04'
      #semantic-release-num: ${{ env.semantic-release-num }}
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Front End
        id: push-img-fe
        env:
          TAG: "${{ env.COHORT }}${{ env.TEAM }}fe-dev-${{ github.run_number }}"
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfiles/Dockerfile_nginx
          push: true
          tags: $ECR_RR:$TAG

      - name: Build and Push DB
        id: build-img-db
        env:
          TAG: "${{ env.COHORT }}${{ env.TEAM }}db-dev-${{ github.run_number }}"
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfiles/Dockerfile_mysql
          push: true
          tags: $ECR_RR:$TAG

      - name: Build and Push API
        id: build-img-api
        env:
          TAG: "${{ env.COHORT }}${{ env.TEAM }}api-dev-${{ github.run_number }}"
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfiles/Dockerfile_api
          push: true
          tags: $ECR_RR:$TAG
