#attempt at deleting existing images - should do ten at a time?? and only for team03
#based on jenkins pipeline file ../utils/pipeline_clean_ecr
#...except that im pretty sure that pipeline just deletes 80 images at a time from the whole class 

name: delete-images
on: 
  push:
    branches:
      - c397team03
  workflow_dispatch: 

jobs:
  DeleteOldImages:
    runs-on: [self-hosted, eks-sre-infra, ubuntu-latest]
    env:
      ECR_REPOSITORY: "production-support-course"
      ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
      COHORT: 'c397'
      TEAM: 'team03'
      #semantic-release-num: ${{ env.semantic-release-num }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: run_delete
        shell: bash
        run: |
          allImages=$(aws ecr list-images --repository-name ${ECR_REPOSITORY} | grep imageTag | awk -F: '{gsub(" ", "\\n", $2); print $2}' | sed 's/\"//g' | grep ${COHORT}${TEAM} | head -n 10 )            
              while [ -n "$allImages" ]
              do
                for tagName in $(echo "$allImages" | head -n 10)
                do
                  images="imageTag=$tagName $images"
                done
                if aws ecr batch-delete-image --repository-name ${ECR_REPOSITORY} --image-ids $images | grep "not found"           
                then
                  exit 0
                fi
                images=""
                sleep 10
                allImages=$(aws ecr list-images --repository-name ${ECR_REPOSITORY} | grep imageTag | awk -F: '{gsub(" ", "\\n", $2); print $2}' | sed 's/\"//g' | grep ${COHORT}${TEAM} | head -n 10 )
                # allImages=""
              done
          
